default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :CI do
    cleanProject
    createDebugBuild
    test
    codeCoverage
  end

  desc "Clean project"
  lane :cleanProject do
    gradle(task: "clean")
  end

  desc "Run all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Create coverage report"
  lane :codeCoverage do
    gradle(task: "testDebugUnitTest")
  end

  desc "Runs all the tests"
  lane :createDebugBuild do
    gradle(task: "assembleDebug")
  end
end
