default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :CI do
    cleanProject
    createDebugBuild
    unitTest
    coverageReport
  end

  desc "Clean project"
  lane :cleanProject do
    gradle(task: "clean")
  end

  desc "Runs all the tests"
  lane :createDebugBuild do
    gradle(task: "assembleDebug")
  end

  desc "Create coverage report"
  lane :unitTest do
    gradle(task: "testDebugUnitTest")
  end

  desc "Create coverage report"
  lane :uiTest do
    gradle(task: "connectedAndroidTest")
  end

  desc "Run all the tests"
  lane :coverageReport do
    gradle(task: "jacocoTestReport")
  end

end
